### ISSUE TITLE
google_explorer

### ISSUE THREAD

**Issue by aliaseel** [paralelo14/google_explorer#12]
Traceback (most recent call last):
  File "google_explorer.py", line 318, in <module>
    main()
  File "google_explorer.py", line 313, in main
    myScan = GoogleScanner(dork, browser, filters)
  File "google_explorer.py", line 82, in __init__
    self.driver = self.validate_browser()
  File "google_explorer.py", line 106, in validate_browser
    driver = webdriver.Chrome(chrome_options=opts)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 4.8.0-kali1-amd64 x86_64)

**Comment by paralelo14** [comment]
Hi, can you take screen shot please?

Are you running as root??

**Comment by aliaseel** [comment]
![aaaa](https://cloud.githubusercontent.com/assets/24368480/20866159/9f249870-ba36-11e6-9ff1-717d17cd3c21.PNG)

**Comment by paralelo14** [comment]
Brother this project is for **python 3**

Please install dependencys as python3 and try to run as python3.
