### ISSUE TITLE
google_explorer.py

### ISSUE THREAD

**Issue by aliaseel** [paralelo14/google_explorer#13]
![aaaa](https://cloud.githubusercontent.com/assets/24368480/20866170/deacce4a-ba36-11e6-8550-0263a7f26de8.PNG)

Traceback (most recent call last):
  File "google_explorer.py", line 318, in <module>
    main()
  File "google_explorer.py", line 313, in main
    myScan = GoogleScanner(dork, browser, filters)
  File "google_explorer.py", line 82, in __init__
    self.driver = self.validate_browser()
  File "google_explorer.py", line 106, in validate_browser
    driver = webdriver.Chrome(chrome_options=opts)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 4.8.0-kali1-amd64 x86_64)

**Comment by paralelo14** [comment]
Brother this project is for **python 3**

Please install dependencys as python3 and try to run as python3.

**Comment by aliaseel** [comment]
![default](https://cloud.githubusercontent.com/assets/24368480/20866571/a5639452-ba40-11e6-916a-1134e2a65c8f.PNG)

  File "google_explorer.py", line 324, in <module>
    main()
  File "google_explorer.py", line 319, in main
    myScan = GoogleScanner(dork, browser, filters)
  File "google_explorer.py", line 88, in __init__
    self.driver = self.validate_browser()
  File "google_explorer.py", line 112, in validate_browser
    driver = webdriver.Chrome(chrome_options=opts)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 4.8.0-kali1-amd64 x86_64)

**Comment by paralelo14** [comment]
Nice make these test for me:

1) Open your terminal, and go to python3 shell : 
$ python3

2) Inside the shell put these code and see if google chrome opens:

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait

browser_path = '/usr/bin/google-chrome-stable'

opts = Options()
opts.binary_location = browser_path
driver = webdriver.Chrome(chrome_options=opts)
driver.wait = WebDriverWait(driver, 20)

**Comment by aliaseel** [comment]
![ssss](https://cloud.githubusercontent.com/assets/24368480/20866713/61a2fff6-ba44-11e6-9b98-cf8bb0f8e414.PNG)

Traceback (most recent call last):
  File "google_explorer.py", line 324, in <module>
    main()
  File "google_explorer.py", line 319, in main
    myScan = GoogleScanner(dork, browser, filters)
  File "google_explorer.py", line 88, in __init__
    self.driver = self.validate_browser()
  File "google_explorer.py", line 112, in validate_browser
    driver = webdriver.Chrome(chrome_options=opts)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 4.8.0-kali1-amd64 x86_64)

**Comment by paralelo14** [comment]
Ok bro, so probably u are getting the same error described here: 

https://github.com/anarcoder/google_explorer/issues/2

The user was running as 'root' and was getting this same error:

"Ahh wait - I think i fixed it :)

Can not be run as root because chrome/chromium wont run as root by default.

As a regular user the app seems to work okay"


So you should use a regular user to run it

**Comment by aliaseel** [comment]
ok
File "google_explorer.py", line 76
SyntaxError: Non-ASCII character '\xe2' in file google_explorer.py on line 76, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by paralelo14** [comment]
Brother last time i say...

**The project is for PYTHON 3 !!!!! You need to INSTALL and RUN as PYTHON 3!!!**
